[Lesson #1] Add Client Side Components
AleksandrKudashkin/reactjs_blog_platform pull request #1
Opened 2017-01-10 03:14 UTC by AleksandrKudashkin

* Add Image component
* Add TextBox component
* Add BlogItem Component
* Add BlogList Component
* Add BlogPage Component

2017-01-14 10:40 UTC, index01d requested changes

2017-01-14 10:40 UTC, index01d commented on BlogList.js
> +    React.createElement(Image, { args: post.imageArgs }),
а почему args? можно отдельно в props передать src, width, height, alt; тогда вторым параметром будет просто post.imageArgs

2017-01-14 10:40 UTC, index01d commented on BlogList.js
> +const Image = ({ args }) => (
см. ниже можно преобразовать в `{ src, width, height, alt }`

2017-01-14 10:40 UTC, index01d commented on BlogList.js
> +    {
тогда здесь будет { src, width, height, alt }

2017-01-14 23:09 UTC, AleksandrKudashkin commented on BlogList.js
> +const Image = ({ args }) => (
Ну, идея была -- избавиться от зависимости от порядка аргументов -- на случай, если я (или другой разработчик) потом забуду, что за чем следует. Имеет смысл раскрыть параметры?

2017-01-15 16:45 UTC, index01d commented on BlogList.js
> +const Image = ({ args }) => (
если использовать деструктурирование объекта ({}), то порядок не имеет значения
`const Image = ({ src, width, height, alt }) => (`
==
`const Image = ({ width, height, src, alt }) => (`

2017-01-15 19:35 UTC, AleksandrKudashkin commented on BlogList.js
> +const Image = ({ args }) => (
Исправил. Я смотрю, что еще и по умолчанию src: src в этом случае можно заменить на просто src, например. Прикольно!

2017-01-15 20:08 UTC, index01d approved these changes

2017-01-16 00:48 UTC, merged