Change BlogPage
AleksandrKudashkin/reactjs_blog_platform pull request #3
Opened 2017-02-14 01:35 UTC by AleksandrKudashkin

Не могу заставить работать первую часть задания. Долго думает (где-то рекурсия, я так понимаю), затем выдает варнинг:
"Warning: setState(...): Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to `componentWillMount`."

В render компонента BlogPage я делаю так const { posts } = this.state 
Так нельзя? Из свойств если брать, тоже самое получается.

2017-02-14 07:28 UTC, index01d requested changes

2017-02-14 07:28 UTC, index01d commented on BlogPage.js
> +            addLike: addLike(post.metaInfo.id)
Вот здесь ты вызываешь функцию при рендеринге, внутри функции ты меняешь состояние, происходит повторный рендеринг и снова вызывается данная функция, снова меняется состояние, снова рендеринг и.т.д. Рекурсия.
`addLike: () => addLike(post.metaInfo.id)` решит проблему

2017-02-15 03:42 UTC, AleksandrKudashkin commented on BlogPage.js
> +            addLike: addLike(post.metaInfo.id)
Да, помогло, спасибо.

2017-02-15 03:50 UTC, AleksandrKudashkin commented
Почему обработчик не инкрементирует default value ? Если у меня для поста likes не задан, подставляется дефолтное значение 0, но после клика на +1 в лайках пишется NaN. В случае, если likes задан - всё работает.

2017-02-15 08:15 UTC, index01d commented
Я не совсем понял вопрос. А почему обработчик должен инкрементировать defaultValue? Чтобы предусмотреть ситуацию, когда у поста нет поля likes, нужно в обработчике явно задавать данный ключ в объекте

2017-02-16 09:56 UTC, index01d approved these changes

2017-02-20 02:50 UTC, merged